require('dotenv').config();
const express = require('express');
const session = require('express-session');
const QRCode = require('qrcode');
const bcrypt = require('bcryptjs');
const multer = require('multer');
const { MongoClient } = require('mongodb');
const { randomUUID } = require('crypto');
const path = require('path');
const { uploadProductImage } = require('./services/media-storage');

const app = express();
const PORT = process.env.PORT || 3000;
const client = new MongoClient(process.env.MONGODB_URI || 'mongodb://localhost:27017/menu');
let database;
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } });
const plans = { monthly: { label: 'Monthly', days: 30, price: 250 }, quarterly: { label: 'Quarterly', days: 90, price: 650 } };

app.set('view engine', 'ejs'); app.set('views', path.join(__dirname, 'views'));
app.use(express.static(path.join(__dirname, 'public'))); app.use(express.urlencoded({ extended: true }));
app.use(session({ secret: process.env.SESSION_SECRET || 'change-me', resave: false, saveUninitialized: false, cookie: { httpOnly: true, sameSite: 'lax' } }));
const asyncRoute = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
const isActive = (r) => (r.status === 'trial' && new Date(r.trialEndsAt) > new Date()) || (r.status === 'active' && new Date(r.subscriptionEndsAt) > new Date());
const daysRemaining = (r) => { const end = r.status === 'trial' ? r.trialEndsAt : r.subscriptionEndsAt; return end ? Math.max(0, Math.ceil((new Date(end) - new Date()) / 86400000)) : 0; };
const slugify = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const publicBaseUrl = (req) => (process.env.PUBLIC_BASE_URL || `${req.protocol}://${req.get('host')}`).replace(/\/+$/, '');
const collection = (name) => database.collection(name);

async function menuFor(restaurant) { const categories = await collection('categories').find({ restaurantId: restaurant.id }).sort({ position: 1 }).toArray(); const products = await collection('products').find({ restaurantId: restaurant.id }).sort({ position: 1 }).toArray(); restaurant.collections = categories.map((category) => ({ ...category, products: products.filter((product) => product.categoryId === category.id).map((product) => ({ ...product, imageUrl: product.imageUrl })) })); return restaurant; }
async function getRestaurantByUser(userId, full = false) { const restaurant = await collection('restaurants').findOne({ ownerId: userId }); if (!restaurant) return null; const user = await collection('users').findOne({ id: userId }); restaurant.email = user?.email; return full ? menuFor(restaurant) : restaurant; }
async function getRestaurantBySlug(slug) { const restaurant = await collection('restaurants').findOne({ slug }); return restaurant ? menuFor(restaurant) : null; }
async function uniqueSlug(name) { const base = slugify(name) || 'restaurant'; let slug = base; let index = 2; while (await collection('restaurants').findOne({ slug })) slug = `${base}-${index++}`; return slug; }
async function initializeDatabase() { await client.connect(); database = client.db(); await Promise.all([collection('users').createIndex({ email: 1 }, { unique: true }), collection('restaurants').createIndex({ slug: 1 }, { unique: true }), collection('restaurants').createIndex({ ownerId: 1 }, { unique: true }), collection('categories').createIndex({ restaurantId: 1 }), collection('products').createIndex({ restaurantId: 1 })]); if (process.env.SUPERADMIN_EMAIL && process.env.SUPERADMIN_PASSWORD) { const email = process.env.SUPERADMIN_EMAIL.toLowerCase(); if (!await collection('users').findOne({ email })) await collection('users').insertOne({ id: randomUUID(), email, passwordHash: await bcrypt.hash(process.env.SUPERADMIN_PASSWORD, 12), role: 'superadmin', createdAt: new Date() }); } }

app.use(asyncRoute(async (req, res, next) => { res.locals.user = req.session.userId ? await getRestaurantByUser(req.session.userId) : null; res.locals.isAdmin = req.session.role === 'superadmin'; res.locals.isActive = res.locals.user && isActive(res.locals.user); next(); }));
const restaurantOnly = asyncRoute(async (req, res, next) => { if (!req.session.userId || req.session.role !== 'restaurant') return res.redirect('/login'); req.restaurant = await getRestaurantByUser(req.session.userId, true); if (!req.restaurant) return res.redirect('/login'); next(); });
const adminOnly = (req, res, next) => req.session.role === 'superadmin' ? next() : res.redirect('/login');

app.get('/', (req, res) => res.render('home', { title: 'Menu' }));
app.get('/signup', (req, res) => res.render('signup', { title: 'Create restaurant account', error: null }));
app.post('/signup', asyncRoute(async (req, res) => { const { name, email, password } = req.body; if (!name || !email || !password) return res.render('signup', { title: 'Create restaurant account', error: 'Please complete every field.' }); const normalizedEmail = email.toLowerCase(); if (await collection('users').findOne({ email: normalizedEmail })) return res.render('signup', { title: 'Create restaurant account', error: 'An account already uses this email.' }); const user = { id: randomUUID(), email: normalizedEmail, passwordHash: await bcrypt.hash(password, 12), role: 'restaurant', createdAt: new Date() }; await collection('users').insertOne(user); await collection('restaurants').insertOne({ id: randomUUID(), ownerId: user.id, name: name.trim(), slogan: null, slug: await uniqueSlug(name), status: 'trial', trialEndsAt: new Date(Date.now() + 5 * 86400000), subscriptionEndsAt: null, selectedPlan: null, paymentStatus: null, createdAt: new Date() }); req.session.userId = user.id; req.session.role = 'restaurant'; res.redirect('/dashboard'); }));
app.get('/login', (req, res) => res.render('login', { title: 'Sign in', error: null }));
app.post('/login', asyncRoute(async (req, res) => { const user = await collection('users').findOne({ email: String(req.body.email).toLowerCase() }); if (!user || !(await bcrypt.compare(req.body.password, user.passwordHash))) return res.render('login', { title: 'Sign in', error: 'Invalid email or password.' }); req.session.userId = user.id; req.session.role = user.role; res.redirect(user.role === 'superadmin' ? '/admin' : '/dashboard'); }));
app.post('/logout', (req, res) => req.session.destroy(() => res.redirect('/')));
app.get('/dashboard', restaurantOnly, (req, res) => res.render('dashboard', { title: 'Dashboard', restaurant: req.restaurant, active: isActive(req.restaurant), days: daysRemaining(req.restaurant), plans }));
app.get('/dashboard/profile', restaurantOnly, (req, res) => res.render('profile-edit', { title: 'Edit profile', restaurant: req.restaurant }));
app.post('/dashboard/profile', restaurantOnly, asyncRoute(async (req, res) => { const name = req.body.name?.trim(); if (!name) return res.redirect('/dashboard/profile'); await collection('restaurants').updateOne({ id: req.restaurant.id }, { $set: { name, slogan: req.body.slogan?.trim() || null } }); res.redirect('/dashboard'); }));
app.get('/dashboard/menu', restaurantOnly, (req, res) => { if (!isActive(req.restaurant)) return res.redirect('/dashboard/subscription'); const productCount = req.restaurant.collections.reduce((sum, item) => sum + item.products.length, 0); res.render('menu-editor', { title: 'Edit menu', restaurant: req.restaurant, collectionCount: req.restaurant.collections.length, productCount }); });
app.post('/dashboard/menu/collection', restaurantOnly, asyncRoute(async (req, res) => { if (!isActive(req.restaurant) || !req.body.name || (req.restaurant.status === 'trial' && req.restaurant.collections.length >= 3)) return res.redirect('/dashboard/menu'); await collection('categories').insertOne({ id: randomUUID(), restaurantId: req.restaurant.id, name: req.body.name.trim(), position: req.restaurant.collections.length }); res.redirect('/dashboard/menu'); }));
app.post('/dashboard/menu/product', restaurantOnly, upload.single('image'), asyncRoute(async (req, res) => { const count = req.restaurant.collections.reduce((sum, item) => sum + item.products.length, 0); const category = req.restaurant.collections.find((item) => item.id === req.body.collectionId); if (!isActive(req.restaurant) || !category || !req.body.name || (req.restaurant.status === 'trial' && count >= 10)) return res.redirect('/dashboard/menu'); await collection('products').insertOne({ id: randomUUID(), restaurantId: req.restaurant.id, categoryId: category.id, name: req.body.name.trim(), description: req.body.description?.trim() || null, price: Number(req.body.price), imageUrl: req.file ? await uploadProductImage(req.file) : null, position: category.products.length }); res.redirect('/dashboard/menu'); }));
app.get('/dashboard/menu/products/:id/edit', restaurantOnly, asyncRoute(async (req, res) => { const product = await collection('products').findOne({ id: req.params.id, restaurantId: req.restaurant.id }); if (!product) return res.redirect('/dashboard/menu'); res.render('product-edit', { title: `Edit ${product.name}`, restaurant: req.restaurant, product }); }));
app.post('/dashboard/menu/products/:id/edit', restaurantOnly, upload.single('image'), asyncRoute(async (req, res) => { const product = await collection('products').findOne({ id: req.params.id, restaurantId: req.restaurant.id }); const category = req.restaurant.collections.find((item) => item.id === req.body.collectionId); if (!product || !category || !req.body.name || !req.body.price) return res.redirect(`/dashboard/menu/products/${req.params.id}/edit`); await collection('products').updateOne({ id: product.id }, { $set: { categoryId: category.id, name: req.body.name.trim(), description: req.body.description?.trim() || null, price: Number(req.body.price), imageUrl: req.file ? await uploadProductImage(req.file) : product.imageUrl } }); res.redirect('/dashboard/menu'); }));
app.get('/dashboard/subscription', restaurantOnly, asyncRoute(async (req, res) => { const payments = await collection('payments').find({ restaurantId: req.restaurant.id }).sort({ submittedAt: -1 }).toArray(); res.render('subscription', { title: 'Subscription', restaurant: req.restaurant, plans, days: daysRemaining(req.restaurant), payments }); }));
app.get('/dashboard/subscription/renew', restaurantOnly, (req, res) => res.render('renew-subscription', { title: 'Renew subscription', restaurant: req.restaurant, plans, bankQrUrl: process.env.BANK_PAYMENT_QR_URL || null }));
app.post('/dashboard/subscription/renew', restaurantOnly, upload.single('paymentImage'), asyncRoute(async (req, res) => { if (!plans[req.body.plan] || !req.file) return res.redirect('/dashboard/subscription/renew'); const paymentImageUrl = await uploadProductImage(req.file); const update = { selectedPlan: req.body.plan, paymentStatus: 'submitted' }; if (!isActive(req.restaurant)) update.status = 'pending'; await collection('restaurants').updateOne({ id: req.restaurant.id }, { $set: update }); await collection('payments').insertOne({ id: randomUUID(), restaurantId: req.restaurant.id, planCode: req.body.plan, reference: req.body.reference?.trim() || null, paymentImageUrl, status: 'submitted', submittedAt: new Date() }); res.redirect('/dashboard/subscription'); }));
app.get('/dashboard/qr', restaurantOnly, asyncRoute(async (req, res) => { if (!isActive(req.restaurant)) return res.redirect('/dashboard/subscription'); const url = `${publicBaseUrl(req)}/menu/${req.restaurant.slug}`; const qr = await QRCode.toDataURL(url, { margin: 1, width: 900, color: { dark: '#f4f2ed', light: '#090909' } }); res.render('qr-card', { title: 'Print QR card', restaurant: req.restaurant, qr, url }); }));
app.get('/menu/:slug', asyncRoute(async (req, res) => { const restaurant = await getRestaurantBySlug(req.params.slug); if (!restaurant || !isActive(restaurant)) return res.status(404).render('unavailable', { title: 'Menu unavailable' }); res.render('public-menu', { title: `${restaurant.name} Menu`, restaurant }); }));
app.get('/admin', adminOnly, asyncRoute(async (req, res) => { const restaurants = await collection('restaurants').find().sort({ createdAt: -1 }).toArray(); const users = await collection('users').find({ role: 'restaurant' }).toArray(); restaurants.forEach((restaurant) => { restaurant.email = users.find((user) => user.id === restaurant.ownerId)?.email; }); res.render('admin', { title: 'Admin', restaurants, plans }); }));
app.post('/admin/restaurants/:id/manage', adminOnly, asyncRoute(async (req, res) => { const status = ['trial', 'pending', 'active', 'suspended'].includes(req.body.status) ? req.body.status : 'suspended'; const update = { status }; if (req.body.expiryDate) { const expiry = new Date(`${req.body.expiryDate}T23:59:59.999Z`); if (!Number.isNaN(expiry.getTime())) update.subscriptionEndsAt = expiry; } await collection('restaurants').updateOne({ id: req.params.id }, { $set: update }); res.redirect('/admin'); }));
app.get('/admin/payments', adminOnly, asyncRoute(async (req, res) => { const payments = await collection('payments').find().sort({ submittedAt: -1 }).toArray(); const restaurants = await collection('restaurants').find().toArray(); const users = await collection('users').find({ role: 'restaurant' }).toArray(); payments.forEach((payment) => { payment.restaurant = restaurants.find((restaurant) => restaurant.id === payment.restaurantId); if (payment.restaurant) payment.restaurant.email = users.find((user) => user.id === payment.restaurant.ownerId)?.email; }); res.render('admin-payments', { title: 'Payment requests', payments, plans }); }));
app.get('/admin/payments/:id', adminOnly, asyncRoute(async (req, res) => { const payment = await collection('payments').findOne({ id: req.params.id }); if (!payment) return res.redirect('/admin/payments'); const restaurant = await collection('restaurants').findOne({ id: payment.restaurantId }); const user = restaurant && await collection('users').findOne({ id: restaurant.ownerId }); res.render('admin-payment-detail', { title: 'Payment details', payment, restaurant, user, plan: plans[payment.planCode] }); }));
app.post('/admin/payments/:id/approve', adminOnly, asyncRoute(async (req, res) => { const payment = await collection('payments').findOne({ id: req.params.id }); const restaurant = payment && await collection('restaurants').findOne({ id: payment.restaurantId }); const plan = payment && plans[payment.planCode]; if (payment && restaurant && plan) { const now = new Date(); const currentExpiry = restaurant.subscriptionEndsAt ? new Date(restaurant.subscriptionEndsAt) : null; const startsAt = currentExpiry && currentExpiry > now ? currentExpiry : now; const endsAt = new Date(startsAt.getTime() + plan.days * 86400000); await collection('payments').updateOne({ id: payment.id }, { $set: { status: 'approved', approvedAt: now } }); await collection('restaurants').updateOne({ id: payment.restaurantId }, { $set: { status: 'active', paymentStatus: 'approved', selectedPlan: payment.planCode, subscriptionEndsAt: endsAt } }); await collection('subscriptions').insertOne({ id: randomUUID(), restaurantId: payment.restaurantId, planCode: payment.planCode, startsAt, endsAt, createdAt: now }); } res.redirect(`/admin/payments/${req.params.id}`); }));
app.post('/admin/restaurants/:id/approve', adminOnly, asyncRoute(async (req, res) => { const restaurant = await collection('restaurants').findOne({ id: req.params.id }); const plan = restaurant && plans[restaurant.selectedPlan]; if (restaurant && plan) { const now = new Date(); const currentExpiry = restaurant.subscriptionEndsAt ? new Date(restaurant.subscriptionEndsAt) : null; const startsAt = currentExpiry && currentExpiry > now ? currentExpiry : now; const endsAt = new Date(startsAt.getTime() + plan.days * 86400000); await collection('restaurants').updateOne({ id: restaurant.id }, { $set: { status: 'active', paymentStatus: 'approved', subscriptionEndsAt: endsAt } }); await collection('payments').updateMany({ restaurantId: restaurant.id, status: 'submitted' }, { $set: { status: 'approved', approvedAt: now } }); await collection('subscriptions').insertOne({ id: randomUUID(), restaurantId: restaurant.id, planCode: restaurant.selectedPlan, startsAt, endsAt, createdAt: now }); } res.redirect('/admin'); }));
app.post('/admin/restaurants/:id/suspend', adminOnly, asyncRoute(async (req, res) => { await collection('restaurants').updateOne({ id: req.params.id }, { $set: { status: 'suspended' } }); res.redirect('/admin'); }));
app.use((error, req, res, next) => { console.error(error); if (error instanceof multer.MulterError) return res.status(400).send('Image upload failed. Images must be smaller than 5 MB.'); res.status(500).send('Something went wrong. Please try again.'); });
initializeDatabase().then(() => app.listen(PORT, () => console.log(`Menu running at http://localhost:${PORT}`))).catch((error) => { console.error('MongoDB connection failed:', error); process.exit(1); });
